apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
    type: back-end
spec:
  template:
    metadata:
      name: spring-boot-app
      labels:
        app: spring-boot
        type: back-end
    spec:
      containers:
        - name: spring-boot-app
          image: "yandihlg/backend-demo:latest"
          imagePullPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
      type: back-end
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: spring-boot-app
#spec:
#  selector:
#    app: spring-boot
#  type: NodePort
#  ports:
#    - protocol: TCP
#      targetPort: 8082
#      port: 8082
#      nodePort: 30001
